require_relative 'pwfmt/context'
require_relative 'pwfmt/helper'
require_relative 'pwfmt/hooks'

require_relative 'pwfmt/patches/ext/string_patch'
require_relative 'pwfmt/patches/ext/wiki_formatting_patch'

require_relative 'pwfmt/patches/helper/application_helper_patch'
require_relative 'pwfmt/patches/helper/textile_helper_patch'
require_relative 'pwfmt/patches/helper/markdown_helper_patch'

require_relative 'pwfmt/patches/controller/application_controller_patch'
require_relative 'pwfmt/patches/controller/documents_controller_patch'
require_relative 'pwfmt/patches/controller/issues_controller_patch'
require_relative 'pwfmt/patches/controller/journals_controller_patch'
require_relative 'pwfmt/patches/controller/messages_controller_patch'
require_relative 'pwfmt/patches/controller/news_controller_patch'
require_relative 'pwfmt/patches/controller/previews_controller_patch'
require_relative 'pwfmt/patches/controller/projects_controller_patch'
require_relative 'pwfmt/patches/controller/settings_controller_patch'
require_relative 'pwfmt/patches/controller/welcome_controller_patch'
require_relative 'pwfmt/patches/controller/wiki_controller_patch'

require_relative 'pwfmt/patches/model/comment_patch'
require_relative 'pwfmt/patches/model/document_patch'
require_relative 'pwfmt/patches/model/issue_patch'
require_relative 'pwfmt/patches/model/journal_patch'
require_relative 'pwfmt/patches/model/message_patch'
require_relative 'pwfmt/patches/model/news_patch'
require_relative 'pwfmt/patches/model/project_patch'
require_relative 'pwfmt/patches/model/setting_patch'
require_relative 'pwfmt/patches/model/wiki_content_patch'
require_relative 'pwfmt/patches/model/wiki_content_version_patch'
